name: threads_client_grpc
version: 0.0.0
description: A gRPC client for interacting with a remote ThreadDB service.
homepage: 'https://github.com/textileio/go-threads'
repository: 'https://github.com/textileio/go-threads'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  async: ^2.2.0
  grpc: ^3.0.2
  protobuf: ^2.0.0
dev_dependencies:
  pubspec_version: ^0.6.1

